from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
import tempfile
import unittest
from typing import Any, Mapping, Sequence
from uuid import uuid4

import psycopg
from psycopg import sql

from mcp_system import (
    EnvironmentSpec,
    MCPSystem,
    Migration,
    PluginManifest,
    PluginRegistry,
    ServiceInstanceSpec,
    TemplateSpec,
)
from mcp_system.plugins import RelationalSession
from mcp_system.storage import PostgresControlPlane, PostgresServiceStorage
from backend_contract import assert_template_clone_contract


@dataclass(frozen=True)
class RelationalTestPlugin:
    manifest: PluginManifest = PluginManifest(
        plugin_id="relational_test",
        version="1.0.0",
        capabilities=("persistent_state",),
    )

    def migrations(self, storage_kind: str) -> Sequence[Migration]:
        if storage_kind != "postgresql":
            raise ValueError(f"unsupported storage kind: {storage_kind}")
        return (
            Migration(
                1,
                (
                    """
                    CREATE TABLE users (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name TEXT NOT NULL UNIQUE
                    )
                    """,
                    """
                    CREATE TABLE items (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        owner_id INTEGER NOT NULL REFERENCES users(id),
                        value TEXT NOT NULL
                    )
                    """,
                ),
            ),
        )

    def validate_bootstrap(self, config: Mapping[str, Any]) -> None:
        return None

    def seed(
        self, session: RelationalSession, config: Mapping[str, Any]
    ) -> None:
        owner = str(config.get("owner", "baseline-user"))
        session.execute(
            "INSERT INTO users(id, name) VALUES (?, ?)", (1, owner)
        )
        session.execute(
            "INSERT INTO items(id, owner_id, value) VALUES (?, ?, ?)",
            (1, 1, "baseline-item"),
        )


class SequentialIds:
    def __init__(self, start: int = 0) -> None:
        self.value = start

    def new_environment_id(self) -> str:
        self.value += 1
        return f"env{self.value:04d}"


@unittest.skipUnless(
    os.getenv("MCP_SYSTEM_TEST_POSTGRES_DSN"),
    "set MCP_SYSTEM_TEST_POSTGRES_DSN to run PostgreSQL integration tests",
)
class PostgresBackendIntegrationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.dsn = os.environ["MCP_SYSTEM_TEST_POSTGRES_DSN"]

    def setUp(self) -> None:
        suffix = uuid4().hex[:10]
        self.control_schema = f"test_control_{suffix}"
        self.storage_namespace = f"test_state_{suffix}"
        self.temp_dir = tempfile.TemporaryDirectory()
        self.registry = PluginRegistry()
        self.registry.register(RelationalTestPlugin())
        self.control = PostgresControlPlane(
            self.dsn, schema=self.control_schema
        )
        self.storage = PostgresServiceStorage(
            self.dsn, namespace=self.storage_namespace
        )
        self.system = MCPSystem(
            Path(self.temp_dir.name),
            self.registry,
            control_plane=self.control,
            service_storage=self.storage,
            ids=SequentialIds(),
        )

    def tearDown(self) -> None:
        with psycopg.connect(self.dsn) as connection:
            rows = connection.execute(
                """
                SELECT nspname FROM pg_namespace
                 WHERE nspname = %s OR nspname LIKE %s
                """,
                (self.control_schema, f"{self.storage_namespace}\\_%"),
            ).fetchall()
            for (schema_name,) in rows:
                connection.execute(
                    sql.SQL("DROP SCHEMA {} CASCADE").format(
                        sql.Identifier(schema_name)
                    )
                )
        self.temp_dir.cleanup()

    def test_template_clone_restart_isolation_and_sequences(self) -> None:
        service = ServiceInstanceSpec(
            instance_id="code_host",
            plugin_id="relational_test",
            plugin_version="1.0.0",
            seed={"owner": "template-user"},
        )
        def restart() -> MCPSystem:
            return MCPSystem(
                Path(self.temp_dir.name),
                self.registry,
                control_plane=PostgresControlPlane(
                    self.dsn, schema=self.control_schema
                ),
                service_storage=PostgresServiceStorage(
                    self.dsn, namespace=self.storage_namespace
                ),
                ids=SequentialIds(start=1),
            )

        def mutate(system: MCPSystem, environment_id: str) -> None:
            with system.open_service_database(environment_id, "code_host") as session:
                created = session.execute(
                    "INSERT INTO items(owner_id, value) VALUES (?, ?) RETURNING id",
                    (1, "first-only"),
                ).fetchone()
            self.assertEqual(created["id"], 2)

        def read(system: MCPSystem, environment_id: str) -> list[tuple[int, str]]:
            with system.open_service_database(environment_id, "code_host") as session:
                rows = session.execute(
                    "SELECT id, value FROM items ORDER BY id"
                ).fetchall()
            return [(row["id"], row["value"]) for row in rows]

        restarted, second_id = assert_template_clone_contract(
            self,
            system=self.system,
            restart=restart,
            template_spec=TemplateSpec(
                template_id="postgres_default",
                name="PostgreSQL template",
                version="1.0.0",
                services=(service,),
                mcp_surfaces=("github_standard",),
            ),
            mutate_first=mutate,
            read_second=read,
            expected_second_state=[(1, "baseline-item")],
        )
        self.assertEqual(
            restarted.list_mcp_surfaces(second_id), ("github_standard",)
        )


if __name__ == "__main__":
    unittest.main()
