"""Relational schema for the bounded Bitbucket Cloud replica."""

from __future__ import annotations

from ...plugins import Migration


def bitbucket_migrations(storage_kind: str) -> tuple[Migration, ...]:
    if storage_kind not in {"sqlite", "postgresql"}:
        raise ValueError(f"unsupported storage kind: {storage_kind}")
    identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY" if storage_kind == "postgresql" else "INTEGER"
    boolean = "BOOLEAN" if storage_kind == "postgresql" else "INTEGER"
    timestamp = "TIMESTAMPTZ" if storage_kind == "postgresql" else "TEXT"
    return (Migration(1, (
        f"""CREATE TABLE bitbucket_users (id {identity} PRIMARY KEY, uuid TEXT NOT NULL UNIQUE, username TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, email TEXT, is_admin {boolean} NOT NULL, created_at {timestamp} NOT NULL)""",
        f"""CREATE TABLE bitbucket_workspaces (id {identity} PRIMARY KEY, uuid TEXT NOT NULL UNIQUE, slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, is_private {boolean} NOT NULL, created_at {timestamp} NOT NULL)""",
        """CREATE TABLE bitbucket_workspace_members (workspace_id BIGINT NOT NULL REFERENCES bitbucket_workspaces(id), user_id BIGINT NOT NULL REFERENCES bitbucket_users(id), permission TEXT NOT NULL, PRIMARY KEY(workspace_id,user_id))""",
        f"""CREATE TABLE bitbucket_repositories (id {identity} PRIMARY KEY, uuid TEXT NOT NULL UNIQUE, workspace_id BIGINT NOT NULL REFERENCES bitbucket_workspaces(id), slug TEXT NOT NULL, name TEXT NOT NULL, description TEXT, is_private {boolean} NOT NULL, mainbranch TEXT NOT NULL, next_issue_id INTEGER NOT NULL, next_pull_request_id INTEGER NOT NULL, next_pipeline_number INTEGER NOT NULL, created_at {timestamp} NOT NULL, updated_at {timestamp} NOT NULL, UNIQUE(workspace_id,slug))""",
        """CREATE TABLE bitbucket_repository_members (repository_id BIGINT NOT NULL REFERENCES bitbucket_repositories(id), user_id BIGINT NOT NULL REFERENCES bitbucket_users(id), permission TEXT NOT NULL, PRIMARY KEY(repository_id,user_id))""",
        f"""CREATE TABLE bitbucket_commits (hash TEXT PRIMARY KEY, repository_id BIGINT NOT NULL REFERENCES bitbucket_repositories(id), message TEXT NOT NULL, author_id BIGINT NOT NULL REFERENCES bitbucket_users(id), committed_at {timestamp} NOT NULL)""",
        """CREATE TABLE bitbucket_commit_parents (commit_hash TEXT NOT NULL REFERENCES bitbucket_commits(hash), parent_hash TEXT NOT NULL REFERENCES bitbucket_commits(hash), position INTEGER NOT NULL, PRIMARY KEY(commit_hash,position))""",
        """CREATE TABLE bitbucket_branches (repository_id BIGINT NOT NULL REFERENCES bitbucket_repositories(id), name TEXT NOT NULL, target_hash TEXT NOT NULL REFERENCES bitbucket_commits(hash), PRIMARY KEY(repository_id,name))""",
        f"""CREATE TABLE bitbucket_issues (id {identity} PRIMARY KEY, repository_id BIGINT NOT NULL REFERENCES bitbucket_repositories(id), local_id INTEGER NOT NULL, title TEXT NOT NULL, content TEXT, state TEXT NOT NULL, kind TEXT NOT NULL, priority TEXT NOT NULL, reporter_id BIGINT NOT NULL REFERENCES bitbucket_users(id), assignee_id BIGINT REFERENCES bitbucket_users(id), created_at {timestamp} NOT NULL, updated_at {timestamp} NOT NULL, UNIQUE(repository_id,local_id))""",
        f"""CREATE TABLE bitbucket_comments (id {identity} PRIMARY KEY, repository_id BIGINT NOT NULL REFERENCES bitbucket_repositories(id), subject_type TEXT NOT NULL, subject_id BIGINT NOT NULL, author_id BIGINT NOT NULL REFERENCES bitbucket_users(id), content TEXT NOT NULL, created_at {timestamp} NOT NULL, updated_at {timestamp} NOT NULL)""",
        f"""CREATE TABLE bitbucket_pull_requests (id {identity} PRIMARY KEY, repository_id BIGINT NOT NULL REFERENCES bitbucket_repositories(id), local_id INTEGER NOT NULL, title TEXT NOT NULL, description TEXT, state TEXT NOT NULL, author_id BIGINT NOT NULL REFERENCES bitbucket_users(id), source_branch TEXT NOT NULL, source_hash TEXT NOT NULL REFERENCES bitbucket_commits(hash), destination_branch TEXT NOT NULL, destination_hash TEXT NOT NULL REFERENCES bitbucket_commits(hash), merge_commit_hash TEXT REFERENCES bitbucket_commits(hash), created_at {timestamp} NOT NULL, updated_at {timestamp} NOT NULL, UNIQUE(repository_id,local_id))""",
        """CREATE TABLE bitbucket_pull_request_reviewers (pull_request_id BIGINT NOT NULL REFERENCES bitbucket_pull_requests(id), user_id BIGINT NOT NULL REFERENCES bitbucket_users(id), state TEXT NOT NULL, PRIMARY KEY(pull_request_id,user_id))""",
        f"""CREATE TABLE bitbucket_pipelines (id {identity} PRIMARY KEY, uuid TEXT NOT NULL UNIQUE, repository_id BIGINT NOT NULL REFERENCES bitbucket_repositories(id), build_number INTEGER NOT NULL, ref_name TEXT NOT NULL, commit_hash TEXT NOT NULL REFERENCES bitbucket_commits(hash), state TEXT NOT NULL, creator_id BIGINT NOT NULL REFERENCES bitbucket_users(id), created_at {timestamp} NOT NULL, completed_at {timestamp}, UNIQUE(repository_id,build_number))""",
        f"""CREATE TABLE bitbucket_pipeline_steps (id {identity} PRIMARY KEY, uuid TEXT NOT NULL UNIQUE, pipeline_id BIGINT NOT NULL REFERENCES bitbucket_pipelines(id), name TEXT NOT NULL, state TEXT NOT NULL, log TEXT NOT NULL, created_at {timestamp} NOT NULL, completed_at {timestamp})""",
        f"""CREATE TABLE bitbucket_commit_statuses (id {identity} PRIMARY KEY, repository_id BIGINT NOT NULL REFERENCES bitbucket_repositories(id), commit_hash TEXT NOT NULL REFERENCES bitbucket_commits(hash), key TEXT NOT NULL, name TEXT NOT NULL, state TEXT NOT NULL, url TEXT, description TEXT, created_at {timestamp} NOT NULL, UNIQUE(repository_id,commit_hash,key))""",
        "CREATE INDEX bitbucket_issues_repo_state ON bitbucket_issues(repository_id,state,updated_at)",
        "CREATE INDEX bitbucket_prs_repo_state ON bitbucket_pull_requests(repository_id,state,updated_at)",
    )),)
