"""Relational schema for the bounded Jira Cloud replica."""

from __future__ import annotations

from ...plugins import Migration


def jira_migrations(storage_kind: str) -> tuple[Migration, ...]:
    if storage_kind not in {"sqlite", "postgresql"}:
        raise ValueError(f"unsupported storage kind: {storage_kind}")
    identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY" if storage_kind == "postgresql" else "INTEGER"
    boolean = "BOOLEAN" if storage_kind == "postgresql" else "INTEGER"
    timestamp = "TIMESTAMPTZ" if storage_kind == "postgresql" else "TEXT"
    return (Migration(1, (
        f"""CREATE TABLE jira_users (
            id {identity} PRIMARY KEY, account_id TEXT NOT NULL UNIQUE,
            display_name TEXT NOT NULL, email TEXT, active {boolean} NOT NULL,
            is_admin {boolean} NOT NULL, created_at {timestamp} NOT NULL
        )""",
        f"""CREATE TABLE jira_projects (
            id {identity} PRIMARY KEY, key TEXT NOT NULL UNIQUE, name TEXT NOT NULL,
            description TEXT, lead_account_id TEXT NOT NULL REFERENCES jira_users(account_id),
            next_issue_number INTEGER NOT NULL, created_at {timestamp} NOT NULL
        )""",
        """CREATE TABLE jira_project_members (
            project_id BIGINT NOT NULL REFERENCES jira_projects(id),
            account_id TEXT NOT NULL REFERENCES jira_users(account_id),
            role TEXT NOT NULL, PRIMARY KEY(project_id, account_id)
        )""",
        f"""CREATE TABLE jira_issues (
            id {identity} PRIMARY KEY, project_id BIGINT NOT NULL REFERENCES jira_projects(id),
            issue_number INTEGER NOT NULL, issue_key TEXT NOT NULL UNIQUE,
            summary TEXT NOT NULL, description TEXT, issue_type TEXT NOT NULL,
            status TEXT NOT NULL, priority TEXT NOT NULL,
            reporter_account_id TEXT NOT NULL REFERENCES jira_users(account_id),
            assignee_account_id TEXT REFERENCES jira_users(account_id),
            resolution TEXT, created_at {timestamp} NOT NULL, updated_at {timestamp} NOT NULL,
            UNIQUE(project_id, issue_number)
        )""",
        """CREATE TABLE jira_issue_labels (
            issue_id BIGINT NOT NULL REFERENCES jira_issues(id), label TEXT NOT NULL,
            PRIMARY KEY(issue_id, label)
        )""",
        f"""CREATE TABLE jira_comments (
            id {identity} PRIMARY KEY, issue_id BIGINT NOT NULL REFERENCES jira_issues(id),
            author_account_id TEXT NOT NULL REFERENCES jira_users(account_id), body TEXT NOT NULL,
            created_at {timestamp} NOT NULL, updated_at {timestamp} NOT NULL
        )""",
        f"""CREATE TABLE jira_issue_links (
            id {identity} PRIMARY KEY, link_type TEXT NOT NULL,
            outward_issue_id BIGINT NOT NULL REFERENCES jira_issues(id),
            inward_issue_id BIGINT NOT NULL REFERENCES jira_issues(id),
            created_at {timestamp} NOT NULL,
            UNIQUE(link_type, outward_issue_id, inward_issue_id)
        )""",
        f"""CREATE TABLE jira_boards (
            id {identity} PRIMARY KEY, name TEXT NOT NULL, board_type TEXT NOT NULL,
            project_id BIGINT NOT NULL REFERENCES jira_projects(id), created_at {timestamp} NOT NULL
        )""",
        f"""CREATE TABLE jira_sprints (
            id {identity} PRIMARY KEY, board_id BIGINT NOT NULL REFERENCES jira_boards(id),
            name TEXT NOT NULL, state TEXT NOT NULL, goal TEXT,
            start_date {timestamp}, end_date {timestamp}, complete_date {timestamp},
            created_at {timestamp} NOT NULL
        )""",
        """CREATE TABLE jira_sprint_issues (
            sprint_id BIGINT NOT NULL REFERENCES jira_sprints(id),
            issue_id BIGINT NOT NULL REFERENCES jira_issues(id),
            PRIMARY KEY(sprint_id, issue_id)
        )""",
        "CREATE INDEX jira_issues_project_status ON jira_issues(project_id, status, updated_at)",
        "CREATE INDEX jira_comments_issue ON jira_comments(issue_id, id)",
    )),)
