"""Relational schema for the bounded GitLab replica."""

from __future__ import annotations

from ...plugins import Migration


def gitlab_migrations(storage_kind: str) -> tuple[Migration, ...]:
    if storage_kind not in {"sqlite", "postgresql"}:
        raise ValueError(f"unsupported storage kind: {storage_kind}")
    identity = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY"
        if storage_kind == "postgresql"
        else "INTEGER"
    )
    boolean = "BOOLEAN" if storage_kind == "postgresql" else "INTEGER"
    timestamp = "TIMESTAMPTZ" if storage_kind == "postgresql" else "TEXT"
    statements = (
        f"""CREATE TABLE gitlab_users (
            id {identity} PRIMARY KEY, username TEXT NOT NULL UNIQUE, name TEXT NOT NULL,
            email TEXT, state TEXT NOT NULL, is_admin {boolean} NOT NULL, created_at {timestamp} NOT NULL
        )""",
        f"""CREATE TABLE gitlab_namespaces (
            id {identity} PRIMARY KEY, name TEXT NOT NULL, path TEXT NOT NULL UNIQUE,
            kind TEXT NOT NULL, visibility TEXT NOT NULL, created_at {timestamp} NOT NULL
        )""",
        """CREATE TABLE gitlab_group_members (
            namespace_id BIGINT NOT NULL REFERENCES gitlab_namespaces(id),
            user_id BIGINT NOT NULL REFERENCES gitlab_users(id), access_level INTEGER NOT NULL,
            PRIMARY KEY(namespace_id, user_id)
        )""",
        f"""CREATE TABLE gitlab_projects (
            id {identity} PRIMARY KEY, namespace_id BIGINT NOT NULL REFERENCES gitlab_namespaces(id),
            name TEXT NOT NULL, path TEXT NOT NULL, path_with_namespace TEXT NOT NULL UNIQUE,
            description TEXT, visibility TEXT NOT NULL, archived {boolean} NOT NULL,
            default_branch TEXT NOT NULL, next_issue_iid INTEGER NOT NULL,
            next_merge_request_iid INTEGER NOT NULL, next_pipeline_iid INTEGER NOT NULL,
            created_at {timestamp} NOT NULL, updated_at {timestamp} NOT NULL,
            UNIQUE(namespace_id, path)
        )""",
        """CREATE TABLE gitlab_project_members (
            project_id BIGINT NOT NULL REFERENCES gitlab_projects(id),
            user_id BIGINT NOT NULL REFERENCES gitlab_users(id), access_level INTEGER NOT NULL,
            PRIMARY KEY(project_id, user_id)
        )""",
        f"""CREATE TABLE gitlab_labels (
            id {identity} PRIMARY KEY, project_id BIGINT NOT NULL REFERENCES gitlab_projects(id),
            name TEXT NOT NULL, color TEXT NOT NULL, description TEXT, UNIQUE(project_id, name)
        )""",
        f"""CREATE TABLE gitlab_issues (
            id {identity} PRIMARY KEY, project_id BIGINT NOT NULL REFERENCES gitlab_projects(id),
            iid INTEGER NOT NULL, title TEXT NOT NULL, description TEXT, state TEXT NOT NULL,
            author_id BIGINT NOT NULL REFERENCES gitlab_users(id), assignee_id BIGINT REFERENCES gitlab_users(id),
            created_at {timestamp} NOT NULL, updated_at {timestamp} NOT NULL, closed_at {timestamp},
            UNIQUE(project_id, iid)
        )""",
        """CREATE TABLE gitlab_issue_labels (
            issue_id BIGINT NOT NULL REFERENCES gitlab_issues(id), label_id BIGINT NOT NULL REFERENCES gitlab_labels(id),
            PRIMARY KEY(issue_id, label_id)
        )""",
        f"""CREATE TABLE gitlab_notes (
            id {identity} PRIMARY KEY, project_id BIGINT NOT NULL REFERENCES gitlab_projects(id),
            noteable_type TEXT NOT NULL, noteable_id BIGINT NOT NULL, author_id BIGINT NOT NULL REFERENCES gitlab_users(id),
            body TEXT NOT NULL, system {boolean} NOT NULL, created_at {timestamp} NOT NULL, updated_at {timestamp} NOT NULL
        )""",
        f"""CREATE TABLE gitlab_commits (
            sha TEXT PRIMARY KEY, project_id BIGINT NOT NULL REFERENCES gitlab_projects(id), tree_sha TEXT,
            message TEXT NOT NULL, author_id BIGINT REFERENCES gitlab_users(id), committed_at {timestamp} NOT NULL
        )""",
        """CREATE TABLE gitlab_commit_parents (
            commit_sha TEXT NOT NULL REFERENCES gitlab_commits(sha), parent_sha TEXT NOT NULL REFERENCES gitlab_commits(sha),
            position INTEGER NOT NULL, PRIMARY KEY(commit_sha, position)
        )""",
        f"""CREATE TABLE gitlab_branches (
            project_id BIGINT NOT NULL REFERENCES gitlab_projects(id), name TEXT NOT NULL,
            head_sha TEXT REFERENCES gitlab_commits(sha), protected {boolean} NOT NULL,
            PRIMARY KEY(project_id, name)
        )""",
        f"""CREATE TABLE gitlab_merge_requests (
            id {identity} PRIMARY KEY, project_id BIGINT NOT NULL REFERENCES gitlab_projects(id), iid INTEGER NOT NULL,
            title TEXT NOT NULL, description TEXT, state TEXT NOT NULL, author_id BIGINT NOT NULL REFERENCES gitlab_users(id),
            source_branch TEXT NOT NULL, source_sha TEXT REFERENCES gitlab_commits(sha),
            target_branch TEXT NOT NULL, target_sha TEXT REFERENCES gitlab_commits(sha), draft {boolean} NOT NULL,
            merged_by_id BIGINT REFERENCES gitlab_users(id), merge_commit_sha TEXT REFERENCES gitlab_commits(sha),
            created_at {timestamp} NOT NULL, updated_at {timestamp} NOT NULL, merged_at {timestamp},
            UNIQUE(project_id, iid)
        )""",
        """CREATE TABLE gitlab_merge_request_reviewers (
            merge_request_id BIGINT NOT NULL REFERENCES gitlab_merge_requests(id),
            user_id BIGINT NOT NULL REFERENCES gitlab_users(id), approved INTEGER NOT NULL,
            PRIMARY KEY(merge_request_id, user_id)
        )""",
        f"""CREATE TABLE gitlab_pipelines (
            id {identity} PRIMARY KEY, project_id BIGINT NOT NULL REFERENCES gitlab_projects(id), iid INTEGER NOT NULL,
            ref TEXT NOT NULL, sha TEXT REFERENCES gitlab_commits(sha), source TEXT NOT NULL, status TEXT NOT NULL,
            user_id BIGINT REFERENCES gitlab_users(id), created_at {timestamp} NOT NULL, updated_at {timestamp} NOT NULL,
            UNIQUE(project_id, iid)
        )""",
        "CREATE INDEX gitlab_issues_project_state ON gitlab_issues(project_id, state, updated_at)",
        "CREATE INDEX gitlab_mrs_project_state ON gitlab_merge_requests(project_id, state, updated_at)",
    )
    extension = (
        f"""CREATE TABLE gitlab_tags (
            project_id BIGINT NOT NULL REFERENCES gitlab_projects(id), name TEXT NOT NULL,
            commit_sha TEXT NOT NULL REFERENCES gitlab_commits(sha), message TEXT,
            created_at {timestamp} NOT NULL, PRIMARY KEY(project_id, name)
        )""",
        f"""CREATE TABLE gitlab_discussions (
            id TEXT PRIMARY KEY, project_id BIGINT NOT NULL REFERENCES gitlab_projects(id),
            noteable_type TEXT NOT NULL, noteable_id BIGINT NOT NULL, resolved {boolean} NOT NULL,
            created_at {timestamp} NOT NULL, updated_at {timestamp} NOT NULL
        )""",
        """CREATE TABLE gitlab_discussion_notes (
            discussion_id TEXT NOT NULL REFERENCES gitlab_discussions(id),
            note_id BIGINT NOT NULL REFERENCES gitlab_notes(id),
            PRIMARY KEY(discussion_id, note_id)
        )""",
        f"""CREATE TABLE gitlab_jobs (
            id {identity} PRIMARY KEY, project_id BIGINT NOT NULL REFERENCES gitlab_projects(id),
            pipeline_id BIGINT NOT NULL REFERENCES gitlab_pipelines(id), name TEXT NOT NULL, stage TEXT NOT NULL,
            status TEXT NOT NULL, allow_failure {boolean} NOT NULL, trace TEXT NOT NULL,
            created_at {timestamp} NOT NULL, started_at {timestamp}, finished_at {timestamp}
        )""",
        f"""CREATE TABLE gitlab_commit_statuses (
            id {identity} PRIMARY KEY, project_id BIGINT NOT NULL REFERENCES gitlab_projects(id),
            commit_sha TEXT NOT NULL REFERENCES gitlab_commits(sha), name TEXT NOT NULL, status TEXT NOT NULL,
            target_url TEXT, description TEXT, creator_id BIGINT NOT NULL REFERENCES gitlab_users(id),
            created_at {timestamp} NOT NULL
        )""",
        f"""CREATE TABLE gitlab_releases (
            id {identity} PRIMARY KEY, project_id BIGINT NOT NULL REFERENCES gitlab_projects(id),
            tag_name TEXT NOT NULL, name TEXT, description TEXT, author_id BIGINT NOT NULL REFERENCES gitlab_users(id),
            created_at {timestamp} NOT NULL, released_at {timestamp} NOT NULL,
            UNIQUE(project_id, tag_name)
        )""",
        "CREATE INDEX gitlab_jobs_pipeline ON gitlab_jobs(pipeline_id, id)",
        "CREATE INDEX gitlab_statuses_commit ON gitlab_commit_statuses(project_id, commit_sha, id)",
    )
    return (Migration(1, statements), Migration(2, extension))
