"""Normalized local persistence schema for the GitHub service replica."""

from __future__ import annotations

from ...plugins import Migration


def github_migrations(storage_kind: str) -> tuple[Migration, ...]:
    refs = ("CREATE TABLE github_tags (repository_id BIGINT NOT NULL REFERENCES github_repositories(id), name TEXT NOT NULL, target_sha TEXT NOT NULL REFERENCES github_commits(sha), PRIMARY KEY(repository_id,name))",)
    if storage_kind == "postgresql":
        return (Migration(1, _postgresql_schema()), Migration(2, ("ALTER TABLE github_workflow_jobs ADD COLUMN log TEXT NOT NULL DEFAULT ''",)), Migration(3, refs))
    if storage_kind == "sqlite":
        return (Migration(1, _sqlite_schema()), Migration(2, ("ALTER TABLE github_workflow_jobs ADD COLUMN log TEXT NOT NULL DEFAULT ''",)), Migration(3, refs))
    raise ValueError(f"unsupported storage kind: {storage_kind}")


def _postgresql_schema() -> tuple[str, ...]:
    return (
        """
        CREATE TABLE github_organizations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            login TEXT NOT NULL,
            name TEXT,
            created_at TIMESTAMPTZ NOT NULL
        )
        """,
        "CREATE UNIQUE INDEX github_org_login_ci ON github_organizations(lower(login))",
        """
        CREATE TABLE github_users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            login TEXT NOT NULL,
            name TEXT,
            email TEXT,
            user_type TEXT NOT NULL DEFAULT 'User' CHECK (user_type IN ('User', 'Bot')),
            site_admin BOOLEAN NOT NULL DEFAULT false,
            created_at TIMESTAMPTZ NOT NULL
        )
        """,
        "CREATE UNIQUE INDEX github_user_login_ci ON github_users(lower(login))",
        """
        CREATE TABLE github_organization_members (
            organization_id BIGINT NOT NULL REFERENCES github_organizations(id),
            user_id BIGINT NOT NULL REFERENCES github_users(id),
            role TEXT NOT NULL CHECK (role IN ('admin', 'member')),
            state TEXT NOT NULL DEFAULT 'active' CHECK (state IN ('active', 'pending')),
            PRIMARY KEY (organization_id, user_id)
        )
        """,
        """
        CREATE TABLE github_repositories (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            owner_organization_id BIGINT NOT NULL REFERENCES github_organizations(id),
            name TEXT NOT NULL,
            full_name TEXT NOT NULL,
            description TEXT,
            private BOOLEAN NOT NULL DEFAULT false,
            archived BOOLEAN NOT NULL DEFAULT false,
            default_branch TEXT NOT NULL DEFAULT 'main',
            next_issue_number INTEGER NOT NULL DEFAULT 1 CHECK (next_issue_number > 0),
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL,
            UNIQUE (owner_organization_id, name)
        )
        """,
        "CREATE UNIQUE INDEX github_repo_full_name_ci ON github_repositories(lower(full_name))",
        """
        CREATE TABLE github_repository_collaborators (
            repository_id BIGINT NOT NULL REFERENCES github_repositories(id),
            user_id BIGINT NOT NULL REFERENCES github_users(id),
            permission TEXT NOT NULL CHECK (permission IN ('pull', 'triage', 'push', 'maintain', 'admin')),
            PRIMARY KEY (repository_id, user_id)
        )
        """,
        """
        CREATE TABLE github_commits (
            sha TEXT PRIMARY KEY,
            repository_id BIGINT NOT NULL REFERENCES github_repositories(id),
            tree_sha TEXT,
            message TEXT NOT NULL,
            author_id BIGINT REFERENCES github_users(id),
            committer_id BIGINT REFERENCES github_users(id),
            authored_at TIMESTAMPTZ NOT NULL,
            committed_at TIMESTAMPTZ NOT NULL
        )
        """,
        "CREATE INDEX github_commits_repo_time ON github_commits(repository_id, committed_at DESC)",
        """
        CREATE TABLE github_commit_parents (
            commit_sha TEXT NOT NULL REFERENCES github_commits(sha),
            parent_sha TEXT NOT NULL REFERENCES github_commits(sha),
            position INTEGER NOT NULL CHECK (position >= 0),
            PRIMARY KEY (commit_sha, position)
        )
        """,
        """
        CREATE TABLE github_branches (
            repository_id BIGINT NOT NULL REFERENCES github_repositories(id),
            name TEXT NOT NULL,
            head_sha TEXT REFERENCES github_commits(sha),
            protected BOOLEAN NOT NULL DEFAULT false,
            PRIMARY KEY (repository_id, name)
        )
        """,
        """
        CREATE TABLE github_labels (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            repository_id BIGINT NOT NULL REFERENCES github_repositories(id),
            name TEXT NOT NULL,
            color TEXT NOT NULL CHECK (color ~ '^[0-9a-fA-F]{6}$'),
            description TEXT,
            is_default BOOLEAN NOT NULL DEFAULT false,
            UNIQUE (repository_id, name)
        )
        """,
        """
        CREATE TABLE github_issues (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            repository_id BIGINT NOT NULL REFERENCES github_repositories(id),
            number INTEGER NOT NULL CHECK (number > 0),
            title TEXT NOT NULL,
            body TEXT,
            state TEXT NOT NULL DEFAULT 'open' CHECK (state IN ('open', 'closed')),
            state_reason TEXT CHECK (state_reason IS NULL OR state_reason IN ('completed', 'not_planned', 'reopened')),
            author_id BIGINT NOT NULL REFERENCES github_users(id),
            locked BOOLEAN NOT NULL DEFAULT false,
            is_pull_request BOOLEAN NOT NULL DEFAULT false,
            comments_count INTEGER NOT NULL DEFAULT 0 CHECK (comments_count >= 0),
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL,
            closed_at TIMESTAMPTZ,
            UNIQUE (repository_id, number)
        )
        """,
        "CREATE INDEX github_issues_repo_state ON github_issues(repository_id, state, updated_at DESC)",
        """
        CREATE TABLE github_issue_labels (
            issue_id BIGINT NOT NULL REFERENCES github_issues(id),
            label_id BIGINT NOT NULL REFERENCES github_labels(id),
            PRIMARY KEY (issue_id, label_id)
        )
        """,
        """
        CREATE TABLE github_issue_assignees (
            issue_id BIGINT NOT NULL REFERENCES github_issues(id),
            user_id BIGINT NOT NULL REFERENCES github_users(id),
            PRIMARY KEY (issue_id, user_id)
        )
        """,
        """
        CREATE TABLE github_issue_comments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            issue_id BIGINT NOT NULL REFERENCES github_issues(id),
            author_id BIGINT NOT NULL REFERENCES github_users(id),
            body TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )
        """,
        "CREATE INDEX github_issue_comments_issue_time ON github_issue_comments(issue_id, created_at)",
        """
        CREATE TABLE github_pull_requests (
            issue_id BIGINT PRIMARY KEY REFERENCES github_issues(id),
            head_ref TEXT NOT NULL,
            head_sha TEXT REFERENCES github_commits(sha),
            base_ref TEXT NOT NULL,
            base_sha TEXT REFERENCES github_commits(sha),
            draft BOOLEAN NOT NULL DEFAULT false,
            mergeable_state TEXT NOT NULL DEFAULT 'unknown' CHECK (mergeable_state IN ('unknown', 'clean', 'dirty', 'blocked', 'unstable', 'behind')),
            merged BOOLEAN NOT NULL DEFAULT false,
            merged_by_id BIGINT REFERENCES github_users(id),
            merged_at TIMESTAMPTZ,
            merge_commit_sha TEXT REFERENCES github_commits(sha)
        )
        """,
        """
        CREATE TABLE github_pull_request_reviewers (
            issue_id BIGINT NOT NULL REFERENCES github_pull_requests(issue_id),
            user_id BIGINT NOT NULL REFERENCES github_users(id),
            PRIMARY KEY (issue_id, user_id)
        )
        """,
        """
        CREATE TABLE github_pull_request_reviews (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            issue_id BIGINT NOT NULL REFERENCES github_pull_requests(issue_id),
            reviewer_id BIGINT NOT NULL REFERENCES github_users(id),
            state TEXT NOT NULL CHECK (state IN ('PENDING', 'APPROVED', 'CHANGES_REQUESTED', 'COMMENTED', 'DISMISSED')),
            body TEXT,
            commit_sha TEXT REFERENCES github_commits(sha),
            submitted_at TIMESTAMPTZ
        )
        """,
        """
        CREATE TABLE github_pull_request_review_comments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            review_id BIGINT REFERENCES github_pull_request_reviews(id),
            issue_id BIGINT NOT NULL REFERENCES github_pull_requests(issue_id),
            author_id BIGINT NOT NULL REFERENCES github_users(id),
            body TEXT NOT NULL,
            path TEXT NOT NULL,
            line INTEGER,
            side TEXT CHECK (side IS NULL OR side IN ('LEFT', 'RIGHT')),
            commit_sha TEXT REFERENCES github_commits(sha),
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )
        """,
        """
        CREATE TABLE github_workflow_runs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            repository_id BIGINT NOT NULL REFERENCES github_repositories(id),
            name TEXT NOT NULL,
            event TEXT NOT NULL,
            status TEXT NOT NULL CHECK (status IN ('queued', 'in_progress', 'completed', 'waiting', 'pending')),
            conclusion TEXT CHECK (conclusion IS NULL OR conclusion IN ('success', 'failure', 'neutral', 'cancelled', 'skipped', 'timed_out', 'action_required', 'stale')),
            head_branch TEXT,
            head_sha TEXT REFERENCES github_commits(sha),
            run_number INTEGER NOT NULL CHECK (run_number > 0),
            run_attempt INTEGER NOT NULL DEFAULT 1 CHECK (run_attempt > 0),
            actor_id BIGINT REFERENCES github_users(id),
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL,
            UNIQUE (repository_id, run_number, run_attempt)
        )
        """,
        """
        CREATE TABLE github_workflow_jobs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id BIGINT NOT NULL REFERENCES github_workflow_runs(id),
            name TEXT NOT NULL,
            status TEXT NOT NULL CHECK (status IN ('queued', 'in_progress', 'completed', 'waiting', 'pending')),
            conclusion TEXT CHECK (conclusion IS NULL OR conclusion IN ('success', 'failure', 'neutral', 'cancelled', 'skipped', 'timed_out', 'action_required', 'stale')),
            started_at TIMESTAMPTZ,
            completed_at TIMESTAMPTZ
        )
        """,
        """
        CREATE TABLE github_releases (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            repository_id BIGINT NOT NULL REFERENCES github_repositories(id),
            tag_name TEXT NOT NULL,
            target_commitish TEXT NOT NULL,
            name TEXT,
            body TEXT,
            draft BOOLEAN NOT NULL DEFAULT false,
            prerelease BOOLEAN NOT NULL DEFAULT false,
            author_id BIGINT NOT NULL REFERENCES github_users(id),
            created_at TIMESTAMPTZ NOT NULL,
            published_at TIMESTAMPTZ,
            UNIQUE (repository_id, tag_name)
        )
        """,
    )


def _sqlite_schema() -> tuple[str, ...]:
    pg = _postgresql_schema()
    converted: list[str] = []
    for statement in pg:
        sqlite = statement
        sqlite = sqlite.replace(
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "INTEGER PRIMARY KEY AUTOINCREMENT",
        )
        sqlite = sqlite.replace("BIGINT", "INTEGER")
        sqlite = sqlite.replace("TIMESTAMPTZ", "TEXT")
        sqlite = sqlite.replace("BOOLEAN", "INTEGER")
        sqlite = sqlite.replace(" DEFAULT false", " DEFAULT 0")
        sqlite = sqlite.replace(" DEFAULT true", " DEFAULT 1")
        sqlite = sqlite.replace(
            " CHECK (color ~ '^[0-9a-fA-F]{6}$')",
            " CHECK (length(color) = 6 AND color NOT GLOB '*[^0-9a-fA-F]*')",
        )
        converted.append(sqlite)
    return tuple(converted)
